#!/usr/bin/env python
"""This module is really used in development if package is not locally installed."""

try:
    from src.masonite_package_sync.main import application
except ImportError:
    from masonite_package_sync.main import application


if __name__ == "__main__":
    application.run()
